# Generated by Django 5.0.7 on 2024-07-16 06:25

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0002_alter_task_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
